import sys
from collections import defaultdict

from yaml import load

try:
    from yaml import CLoader as Loader
except ImportError:
    from yaml import Loader


_ESCAPES = {
    "_": "_u",  # must be first
    "/": "_s",
    ":": "_c",
    "@": "_a",
    "\\": "_b",
    "-": "_d",
}


# Map to the internal, escaped convention used by our fawltydeps tooling
def escape(s: str) -> str:
    s = f"package@py_deps//{s}"
    for k, v in _ESCAPES.items():
        s = s.replace(k, v)
    return s


# Load the imports mapping generated by rules_python pip rule.
with open(sys.argv[1]) as f:
    data = load(f, Loader=Loader)
data = data["manifest"]["modules_mapping"]

# We need to transpose the data, from a mapping of import path to a package
# we generate a mapping of package names to their toplevel import lists.
mappings = defaultdict(set)
for import_path, package_name in data.items():
    mappings[escape(package_name)].add(import_path.split(".")[0])

# Generate the output TOML file understood by fawltydeps.
for package_name, toplevel_imports in mappings.items():
    # Skip packages related to pytest
    if "pytest" in package_name:
        continue

    # Poor man's TOML encoding
    print(f"{repr(package_name)} = {list(toplevel_imports)}")
