from collections import defaultdict
import json
import sys


_ESCAPES = {
    "_": "_u",  # must be first
    "/": "_s",
    ":": "_c",
    "@": "_a",
    "\\": "_b",
    "-": "_d",
}


# Map to the internal, escaped convention used by our fawltydeps tooling
def escape(s: str) -> str:
    s = f"package@{pip_repo_name}//{s}"
    for k, v in _ESCAPES.items():
        s = s.replace(k, v)
    return s


if __name__ == "__main__":
    # Load the imports mapping generated by modules_mapping rule.
    with open(sys.argv[1]) as f:
        data = json.load(f)

    # We need to transpose the datai: From a mapping of import path to package
    # we generate a mapping of package names to their toplevel import list.
    mappings = defaultdict(set)
    for import_path, package_name in data.items():
        mappings[escape(package_name)].add(import_path.split(".")[0])

    # Generate the output TOML file understood by fawltydeps.
    for package_name, toplevel_imports in mappings.items():
        # Poor man's TOML encoding
        print(f"{repr(package_name)} = {list(toplevel_imports)}")
